In [1]:
import pandas as pd
import sqlite3

In [3]:
conn = sqlite3.connect("../database/olist.db")

In [4]:
def run_query(file_name):
    with open(f"../sql/{file_name}", "r", encoding="utf-8") as file:
        query = file.read()

    return pd.read_sql(query, conn)

In [5]:
run_query("01_total_revenue.sql")

   total_revenue
0     16643731.3

In [6]:
run_query("02_total_orders.sql")

   total_orders
0         99441

In [7]:
run_query("03_total_customers.sql")

   total_customers
0            96096

In [8]:
run_query("04_average_order_value.sql")

   average_order_value
0               167.37

In [9]:
run_query("05_top_categories.sql")

  product_category_name_english  total_revenue
0                 health_beauty     1491397.76
1                 watches_gifts     1358845.59
2                bed_bath_table     1327662.02
3                sports_leisure     1205197.85
4         computers_accessories     1104362.03
5               furniture_decor      955367.22
6                    housewares      823623.50
7                    cool_stuff      752702.21
8                          auto      714431.95
9                  garden_tools      625387.31

In [11]:
run_query("06_top_states.sql")

  customer_state  total_revenue
0             SP     6234533.82
1             RJ     2247128.32
2             MG     1928571.09
3             RS      934286.75
4             PR      832059.40
5             BA      650220.38
6             SC      632514.14
7             GO      368997.61
8             DF      367750.15
9             ES      336438.54

In [13]:
run_query("07_payment_methods.sql")

  payment_type  total_transactions
0  credit_card               87776
1       boleto               23190
2      voucher                6465
3   debit_card                1706
4  not_defined                   3
5          NaN                   3

In [14]:
run_query("09_review_scores.sql")

   review_score  total_reviews
0           NaN            997
1           1.0          15428
2           2.0           4162
3           3.0           9894
4           4.0          22319
5           5.0          66343

In [15]:
run_query("10_top_customers.sql")

                 customer_unique_id  total_spent
0  0a0a92112bd4c708ca5fde585afaa872     13664.08
1  8af7ac63b2efbcbd88e5b11505e8098a     13281.71
2  c4b224d2c784bae11ae98b6ae9f2454c     11111.40
3  85963fd37bfd387aa6d915d8a1065486     10553.28
4  be74c431147c32ab2d7c7cef5e4a995f     10055.22
5  edf81e1f3070b9dac83ec83dacdbb9bc      8389.52
6  58483a1c055dfb600f57c5b867174542      8068.88
7  1033eef37a760a832f9b2332ce23fdc5      8030.46
8  da122df9eeddfedc1dc1f5349a1a690c      7571.63
9  301d1ce5a76b7e1bc47e5115bf5eb6ba      7413.70

In [23]:
run_query("11_monthly_revenue.sql")

      month  monthly_revenue
0   2016-09           354.75
1   2016-10         58730.85
2   2016-12            19.62
3   2017-01        148030.11
4   2017-02        303648.31
5   2017-03        459778.64
6   2017-04        449707.81
7   2017-05        634762.22
8   2017-06        531052.06
9   2017-07        631341.57
10  2017-08        706168.95
11  2017-09        767325.70
12  2017-10        808911.33
13  2017-11       1232074.30
14  2017-12        898427.92
15  2018-01       1158742.84
16  2018-02       1039011.65
17  2018-03       1209080.30
18  2018-04       1201102.21
19  2018-05       1193204.98
20  2018-06       1075753.44
21  2018-07       1097939.54
22  2018-08       1038395.74
23  2018-09           166.46
24  2018-10              NaN

In [25]:
run_query("12_monthly_growth.sql")

      month  monthly_revenue  growth_percentage
0   2016-09           354.75                NaN
1   2016-10         58730.85           16455.56
2   2016-12            19.62             -99.97
3   2017-01        148030.11          754385.78
4   2017-02        303648.31             105.13
5   2017-03        459778.64              51.42
6   2017-04        449707.81              -2.19
7   2017-05        634762.22              41.15
8   2017-06        531052.06             -16.34
9   2017-07        631341.57              18.89
10  2017-08        706168.95              11.85
11  2017-09        767325.70               8.66
12  2017-10        808911.33               5.42
13  2017-11       1232074.30              52.31
14  2017-12        898427.92             -27.08
15  2018-01       1158742.84              28.97
16  2018-02       1039011.65             -10.33
17  2018-03       1209080.30              16.37
18  2018-04       1201102.21              -0.66
19  2018-05       1193204.98              -0.66
20  2018-06       1075753.44              -9.84
21  2018-07       1097939.54               2.06
22  2018-08       1038395.74              -5.42
23  2018-09           166.46             -99.98
24  2018-10              NaN                NaN

In [26]:
run_query("13_customer_ranking.sql")

                  customer_unique_id  total_spent  customer_rank
0   0a0a92112bd4c708ca5fde585afaa872     13664.08              1
1   8af7ac63b2efbcbd88e5b11505e8098a     13281.71              2
2   c4b224d2c784bae11ae98b6ae9f2454c     11111.40              3
3   85963fd37bfd387aa6d915d8a1065486     10553.28              4
4   be74c431147c32ab2d7c7cef5e4a995f     10055.22              5
5   edf81e1f3070b9dac83ec83dacdbb9bc      8389.52              6
6   58483a1c055dfb600f57c5b867174542      8068.88              7
7   1033eef37a760a832f9b2332ce23fdc5      8030.46              8
8   da122df9eeddfedc1dc1f5349a1a690c      7571.63              9
9   301d1ce5a76b7e1bc47e5115bf5eb6ba      7413.70             10
10  763c8b1c9c68a0229c42c9fc6f662b93      7274.88             11
11  7f6fd66526ed914998d483cff9b7bdd7      7179.97             12
12  dc4802a71eae9be1dd28f5d788ceb526      6929.31             13
13  459bef486812aa25204be022145caa62      6922.21             14
14  ff4159b92c40ebe40454e3e6a7c35ed6      6726.66             15
15  7a96eb0a685f5c19b7dad29fc802aa64      6594.80             16
16  fd7069cf6891edbf32ba84c9c3f083d4      6511.80             17
17  f9ae226291893fda10af7965268fb7f6      6157.17             18
18  4007669dec559734d6f53e029e360987      6081.54             19
19  60b2ec19b8c18082cdb5180106a97cb5      5385.64             20

In [27]:
run_query("14_pareto_analysis.sql")

,customer_state,customer_unique_id,total_spent,state_rank
0,AC,086d6b5b5ba195a91aa0a6ec8e75d1a4,1990.36,1
1,AC,62a459e5629b03dd73134964df732077,1251.70,2
2,AC,3947ca729a860c522a64a49d762baada,905.93,3
3,AC,3e5c928acf49c4b95e57af1f350d3493,861.26,4
4,AC,28989ef45087c96e5a4346e88216c2ba,723.14,5
...,...,...,...,...
96131,TO,d7241ab927206d28af21ddc3970bc6c9,38.12,263
96132,TO,26e8d473fbaef56f0f90930bb036fb89,37.12,264
96133,TO,139bcc7fa9b38babbf3054cd13e98eb5,35.53,265
96134,TO,e10142a5628ef46a46277528061e78a6,28.77,266
96135,TO,cbd2fdeb27b04ebb48ea691a7cfd4023,NaN,267

In [29]:
run_query("15_cte_example.sql")

      month  monthly_revenue  cumulative_revenue
0   2016-09           354.75              354.75
1   2016-10         58730.85            59085.60
2   2016-12            19.62            59105.22
3   2017-01        148030.11           207135.33
4   2017-02        303648.31           510783.64
5   2017-03        459778.64           970562.28
6   2017-04        449707.81          1420270.09
7   2017-05        634762.22          2055032.31
8   2017-06        531052.06          2586084.37
9   2017-07        631341.57          3217425.94
10  2017-08        706168.95          3923594.89
11  2017-09        767325.70          4690920.59
12  2017-10        808911.33          5499831.92
13  2017-11       1232074.30          6731906.22
14  2017-12        898427.92          7630334.14
15  2018-01       1158742.84          8789076.98
16  2018-02       1039011.65          9828088.63
17  2018-03       1209080.30         11037168.93
18  2018-04       1201102.21         12238271.14
19  2018-05       1193204.98         13431476.12
20  2018-06       1075753.44         14507229.56
21  2018-07       1097939.54         15605169.10
22  2018-08       1038395.74         16643564.84
23  2018-09           166.46         16643731.30
24  2018-10              NaN         16643731.30

In [30]:
run_query("16_pareto_customers.sql")

                     customer_unique_id  total_revenue  cumulative_percentage
0      0a0a92112bd4c708ca5fde585afaa872       13664.08                   0.08
1      8af7ac63b2efbcbd88e5b11505e8098a       13281.71                   0.16
2      c4b224d2c784bae11ae98b6ae9f2454c       11111.40                   0.23
3      85963fd37bfd387aa6d915d8a1065486       10553.28                   0.29
4      be74c431147c32ab2d7c7cef5e4a995f       10055.22                   0.35
...                                 ...            ...                    ...
96091  feb643dc81ca576d83810f147e0e089c            NaN                 100.00
96092  fec36733d170d71e390acde47d74c6d6            NaN                 100.00
96093  ff222edf83338ca6b35f8e29871fa07a            NaN                 100.00
96094  ff28720521c749234b1ba19c9c986f4c            NaN                 100.00
96095  ffb5431b49b42c9f3209f087e1bfdcfa            NaN                 100.00

[96096 rows x 3 columns]

In [31]:
run_query("17_customer_contribution.sql")

                     customer_unique_id  total_revenue  revenue_percentage
0      0a0a92112bd4c708ca5fde585afaa872       13664.08              0.0821
1      8af7ac63b2efbcbd88e5b11505e8098a       13281.71              0.0798
2      c4b224d2c784bae11ae98b6ae9f2454c       11111.40              0.0668
3      85963fd37bfd387aa6d915d8a1065486       10553.28              0.0634
4      be74c431147c32ab2d7c7cef5e4a995f       10055.22              0.0604
...                                 ...            ...                 ...
96091  feb643dc81ca576d83810f147e0e089c            NaN                 NaN
96092  fec36733d170d71e390acde47d74c6d6            NaN                 NaN
96093  ff222edf83338ca6b35f8e29871fa07a            NaN                 NaN
96094  ff28720521c749234b1ba19c9c986f4c            NaN                 NaN
96095  ffb5431b49b42c9f3209f087e1bfdcfa            NaN                 NaN

[96096 rows x 3 columns]

In [32]:
run_query("18_abc_product_analysis.sql")

   product_category_name_english  total_revenue
0                  health_beauty     1491397.76
1                  watches_gifts     1358845.59
2                 bed_bath_table     1327662.02
3                 sports_leisure     1205197.85
4          computers_accessories     1104362.03
..                           ...            ...
67                       flowers        1598.91
68                home_comfort_2        1194.44
69             cds_dvds_musicals         954.99
70     fashion_childrens_clothes         665.36
71         security_and_services         324.51

[72 rows x 2 columns]

In [33]:
run_query("19_top_20_percent_customers.sql")

                     customer_unique_id  total_revenue  customer_group
0      0a0a92112bd4c708ca5fde585afaa872       13664.08               1
1      8af7ac63b2efbcbd88e5b11505e8098a       13281.71               1
2      c4b224d2c784bae11ae98b6ae9f2454c       11111.40               1
3      85963fd37bfd387aa6d915d8a1065486       10553.28               1
4      be74c431147c32ab2d7c7cef5e4a995f       10055.22               1
...                                 ...            ...             ...
19215  c61a15e59e35503a062589d1b609af8d         215.81               1
19216  d58103285e4a2a61cce23e3825700ebd         215.80               1
19217  cf9dee1201f8413d6618ebf94dc94301         215.80               1
19218  7df5f97f9dc003369b506e93a2902840         215.80               1
19219  d35ff7e26bfdc97d1e57191f1438fcfd         215.78               1

[19220 rows x 3 columns]

In [34]:
run_query("20_cte_examples.sql")

   customer_state  total_revenue
0              SP     6234533.82
1              RJ     2247128.32
2              MG     1928571.09
3              RS      934286.75
4              PR      832059.40
5              BA      650220.38
6              SC      632514.14
7              GO      368997.61
8              DF      367750.15
9              ES      336438.54
10             PE      334467.37
11             CE      290599.59
12             PA      224924.18
13             MT      203768.97
14             MA      155510.26
15             PB      151482.79
16             MS      141346.92
17             RN      114747.31
18             PI      114729.56
19             AL       99781.70
20             SE       75495.89
21             TO       69702.51
22             RO       58681.50
23             AM       28549.04
24             AC       20861.50
25             AP       16517.39
26             RR       10064.62